#!/usr/bin/env python3
"""Build the compact AGI-relevant organization/person registry candidate set."""
from __future__ import annotations

import json
from pathlib import Path

ORGANIZATIONS = [
    ("openai", "OpenAI", "frontier-ai-lab", "https://openai.com/news/"),
    ("anthropic", "Anthropic", "frontier-ai-lab", "https://www.anthropic.com/news"),
    ("google-deepmind", "Google DeepMind", "frontier-ai-lab", "https://deepmind.google/discover/blog/"),
    ("google-research", "Google Research", "industry-research-lab", "https://research.google/blog/"),
    ("microsoft-research", "Microsoft Research", "industry-research-lab", "https://www.microsoft.com/en-us/research/blog/"),
    ("microsoft-ai", "Microsoft AI", "frontier-ai-lab", "https://microsoft.ai/news/"),
    ("meta-ai", "Meta AI", "industry-research-lab", "https://ai.meta.com/blog/"),
    ("xai", "xAI", "frontier-ai-lab", "https://x.ai/news"),
    ("mistral-ai", "Mistral AI", "frontier-ai-lab", "https://mistral.ai/news"),
    ("cohere", "Cohere", "frontier-ai-lab", "https://cohere.com/blog"),
    ("ai21-labs", "AI21 Labs", "frontier-ai-lab", "https://www.ai21.com/blog/"),
    ("aleph-alpha", "Aleph Alpha", "frontier-ai-lab", "https://aleph-alpha.com/newsroom/"),
    ("inflection-ai", "Inflection AI", "frontier-ai-lab", "https://inflection.ai/news"),
    ("safe-superintelligence", "Safe Superintelligence Inc.", "frontier-ai-lab", "https://ssi.inc/"),
    ("thinking-machines-lab", "Thinking Machines Lab", "frontier-ai-lab", "https://thinkingmachines.ai/"),
    ("world-labs", "World Labs", "frontier-ai-lab", "https://www.worldlabs.ai/blog"),
    ("physical-intelligence", "Physical Intelligence", "embodied-ai-lab", "https://www.physicalintelligence.company/blog"),
    ("sakana-ai", "Sakana AI", "frontier-ai-lab", "https://sakana.ai/blog/"),
    ("deepseek", "DeepSeek", "frontier-ai-lab", "https://www.deepseek.com/"),
    ("zhipu-ai", "Zhipu AI", "frontier-ai-lab", "https://www.zhipuai.cn/en/news"),
    ("moonshot-ai", "Moonshot AI", "frontier-ai-lab", "https://www.moonshot.cn/"),
    ("baichuan-ai", "Baichuan AI", "frontier-ai-lab", "https://www.baichuan-ai.com/home"),
    ("minimax", "MiniMax", "frontier-ai-lab", "https://www.minimax.io/news"),
    ("01-ai", "01.AI", "frontier-ai-lab", "https://www.01.ai/"),
    ("qwen", "Qwen", "foundation-model-team", "https://qwenlm.github.io/blog/"),
    ("stepfun", "StepFun", "frontier-ai-lab", "https://www.stepfun.com/"),
    ("nvidia-research", "NVIDIA Research", "industry-research-lab", "https://research.nvidia.com/"),
    ("nvidia-ai", "NVIDIA AI", "ai-compute-platform", "https://blogs.nvidia.com/blog/category/deep-learning/"),
    ("apple-machine-learning-research", "Apple Machine Learning Research", "industry-research-lab", "https://machinelearning.apple.com/"),
    ("amazon-science", "Amazon Science", "industry-research-lab", "https://www.amazon.science/blog"),
    ("ibm-research", "IBM Research", "industry-research-lab", "https://research.ibm.com/blog"),
    ("salesforce-ai-research", "Salesforce AI Research", "industry-research-lab", "https://www.salesforceairesearch.com/"),
    ("adobe-research", "Adobe Research", "industry-research-lab", "https://research.adobe.com/news/"),
    ("intel-labs", "Intel Labs", "industry-research-lab", "https://www.intel.com/content/www/us/en/research/overview.html"),
    ("samsung-ai", "Samsung AI", "industry-research-lab", "https://research.samsung.com/news"),
    ("sony-ai", "Sony AI", "industry-research-lab", "https://ai.sony/blog/"),
    ("uber-ai", "Uber AI", "industry-research-lab", "https://www.uber.com/blog/research/"),
    ("bytedance-research", "ByteDance Research", "industry-research-lab", "https://research.bytedance.com/"),
    ("tencent-ai-lab", "Tencent AI Lab", "industry-research-lab", "https://ai.tencent.com/ailab/en/news/"),
    ("baidu-research", "Baidu Research", "industry-research-lab", "https://research.baidu.com/Blog"),
    ("huawei-noahs-ark-lab", "Huawei Noah's Ark Lab", "industry-research-lab", "https://www.noahlab.com.hk/#/news"),
    ("naver-ai-lab", "NAVER AI Lab", "industry-research-lab", "https://naver-ai.github.io/"),
    ("rakuten-institute-of-technology", "Rakuten Institute of Technology", "industry-research-lab", "https://rit.rakuten.com/"),
    ("allen-institute-for-ai", "Allen Institute for AI", "nonprofit-research-lab", "https://allenai.org/news"),
    ("eleutherai", "EleutherAI", "open-research-collective", "https://blog.eleuther.ai/"),
    ("laion", "LAION", "open-research-nonprofit", "https://laion.ai/blog/"),
    ("hugging-face", "Hugging Face", "open-ai-platform", "https://huggingface.co/blog"),
    ("stability-ai", "Stability AI", "generative-ai-lab", "https://stability.ai/news"),
    ("runway", "Runway", "generative-ai-lab", "https://runwayml.com/news"),
    ("midjourney", "Midjourney", "generative-ai-lab", "https://www.midjourney.com/updates"),
    ("black-forest-labs", "Black Forest Labs", "generative-ai-lab", "https://bfl.ai/announcements"),
    ("ideogram", "Ideogram", "generative-ai-lab", "https://about.ideogram.ai/updates"),
    ("elevenlabs", "ElevenLabs", "generative-ai-lab", "https://elevenlabs.io/blog"),
    ("suno", "Suno", "generative-ai-lab", "https://suno.com/blog"),
    ("reka-ai", "Reka AI", "frontier-ai-lab", "https://www.reka.ai/news"),
    ("together-ai", "Together AI", "ai-infrastructure-platform", "https://www.together.ai/blog"),
    ("groq", "Groq", "ai-compute-platform", "https://groq.com/blog"),
    ("cerebras-systems", "Cerebras Systems", "ai-compute-platform", "https://www.cerebras.ai/blog"),
    ("sambanova-systems", "SambaNova Systems", "ai-compute-platform", "https://sambanova.ai/blog"),
    ("graphcore", "Graphcore", "ai-compute-platform", "https://www.graphcore.ai/posts"),
    ("tenstorrent", "Tenstorrent", "ai-compute-platform", "https://tenstorrent.com/en/vision/blog"),
    ("coreweave", "CoreWeave", "ai-cloud-platform", "https://www.coreweave.com/blog"),
    ("lambda", "Lambda", "ai-cloud-platform", "https://lambda.ai/blog"),
    ("scale-ai", "Scale AI", "ai-data-platform", "https://scale.com/blog"),
    ("databricks-mosaic-research", "Databricks Mosaic Research", "industry-research-lab", "https://www.databricks.com/blog/category/engineering/machine-learning"),
    ("snorkel-ai", "Snorkel AI", "ai-data-platform", "https://snorkel.ai/blog/"),
    ("weights-and-biases", "Weights & Biases", "ml-developer-platform", "https://wandb.ai/fully-connected"),
    ("langchain", "LangChain", "agent-platform", "https://blog.langchain.com/"),
    ("llamaindex", "LlamaIndex", "agent-platform", "https://www.llamaindex.ai/blog"),
    ("anyscale", "Anyscale", "ai-infrastructure-platform", "https://www.anyscale.com/blog"),
    ("modal", "Modal", "ai-infrastructure-platform", "https://modal.com/blog"),
    ("replicate", "Replicate", "model-hosting-platform", "https://replicate.com/blog"),
    ("pinecone", "Pinecone", "vector-database", "https://www.pinecone.io/blog/"),
    ("weaviate", "Weaviate", "vector-database", "https://weaviate.io/blog"),
    ("milvus", "Milvus", "vector-database", "https://milvus.io/blog"),
    ("adept-ai", "Adept AI", "agentic-ai-lab", "https://www.adept.ai/blog"),
    ("improbable", "Improbable", "simulation-ai-company", "https://www.improbable.io/blog"),
    ("wayve", "Wayve", "embodied-ai-company", "https://wayve.ai/thinking/"),
    ("waabi", "Waabi", "embodied-ai-company", "https://waabi.ai/news/"),
    ("waymo", "Waymo", "autonomous-systems-lab", "https://waymo.com/blog/"),
    ("cruise", "Cruise", "autonomous-systems-lab", "https://www.getcruise.com/news/"),
    ("tesla-ai", "Tesla AI", "embodied-ai-company", "https://www.tesla.com/AI"),
    ("boston-dynamics", "Boston Dynamics", "robotics-ai-company", "https://bostondynamics.com/blog/"),
    ("figure-ai", "Figure AI", "robotics-ai-company", "https://www.figure.ai/news"),
    ("agility-robotics", "Agility Robotics", "robotics-ai-company", "https://www.agilityrobotics.com/news"),
    ("sanctuary-ai", "Sanctuary AI", "robotics-ai-company", "https://www.sanctuary.ai/blog"),
    ("1x-technologies", "1X Technologies", "robotics-ai-company", "https://www.1x.tech/discover"),
    ("covariant", "Covariant", "robotics-ai-company", "https://covariant.ai/insights/"),
    ("skild-ai", "Skild AI", "robotics-ai-company", "https://www.skild.ai/blog"),
    ("field-ai", "Field AI", "robotics-ai-company", "https://www.fieldai.com/news"),
    ("open-robotics", "Open Robotics", "robotics-foundation", "https://www.openrobotics.org/blog"),
    ("future-of-life-institute", "Future of Life Institute", "ai-governance-nonprofit", "https://futureoflife.org/news/"),
    ("center-for-ai-safety", "Center for AI Safety", "ai-safety-nonprofit", "https://safe.ai/blog"),
    ("machine-intelligence-research-institute", "Machine Intelligence Research Institute", "ai-safety-research-nonprofit", "https://intelligence.org/research/"),
    ("alignment-research-center", "Alignment Research Center", "ai-safety-research-nonprofit", "https://www.alignment.org/blog/"),
    ("redwood-research", "Redwood Research", "ai-safety-research-nonprofit", "https://www.redwoodresearch.org/research"),
    ("apollo-research", "Apollo Research", "ai-safety-research-nonprofit", "https://www.apolloresearch.ai/blog"),
    ("far-ai", "FAR.AI", "ai-safety-research-nonprofit", "https://far.ai/news"),
    ("metr", "METR", "ai-evaluation-nonprofit", "https://metr.org/blog/"),
    ("epoch-ai", "Epoch AI", "ai-trends-research-nonprofit", "https://epoch.ai/blog"),
    ("ai-now-institute", "AI Now Institute", "ai-policy-research-nonprofit", "https://ainowinstitute.org/news"),
    ("partnership-on-ai", "Partnership on AI", "ai-governance-nonprofit", "https://partnershiponai.org/news/"),
    ("center-for-security-and-emerging-technology", "Center for Security and Emerging Technology", "ai-policy-research-center", "https://cset.georgetown.edu/news/"),
    ("stanford-hai", "Stanford Institute for Human-Centered AI", "university-ai-institute", "https://hai.stanford.edu/news"),
    ("stanford-ai-lab", "Stanford Artificial Intelligence Laboratory", "university-ai-lab", "https://ai.stanford.edu/blog/"),
    ("berkeley-ai-research", "Berkeley Artificial Intelligence Research", "university-ai-lab", "https://bair.berkeley.edu/blog/"),
    ("mit-csail", "MIT CSAIL", "university-ai-lab", "https://www.csail.mit.edu/news"),
    ("mit-quest-for-intelligence", "MIT Quest for Intelligence", "university-ai-institute", "https://quest.mit.edu/news/"),
    ("carnegie-mellon-machine-learning", "CMU Machine Learning Department", "university-ai-department", "https://www.ml.cmu.edu/news/index.html"),
    ("princeton-ai-lab", "Princeton AI Lab", "university-ai-lab", "https://ai.princeton.edu/news"),
    ("harvard-kempner-institute", "Kempner Institute for the Study of Natural and Artificial Intelligence", "university-ai-institute", "https://kempnerinstitute.harvard.edu/news/"),
    ("nyu-center-for-data-science", "NYU Center for Data Science", "university-ai-institute", "https://cds.nyu.edu/news/"),
    ("montreal-institute-for-learning-algorithms", "Mila", "independent-ai-institute", "https://mila.quebec/en/news"),
    ("vector-institute", "Vector Institute", "independent-ai-institute", "https://vectorinstitute.ai/news/"),
    ("amii", "Alberta Machine Intelligence Institute", "independent-ai-institute", "https://www.amii.ca/latest-from-amii"),
    ("ellis", "ELLIS", "european-ai-network", "https://ellis.eu/news"),
    ("tuebingen-ai-center", "Tübingen AI Center", "university-ai-center", "https://tuebingen.ai/news"),
    ("dfki", "German Research Center for Artificial Intelligence", "public-ai-research-institute", "https://www.dfki.de/en/web/news-media/news-events"),
    ("inria", "Inria", "public-computer-science-institute", "https://www.inria.fr/en/news"),
    ("riken-aip", "RIKEN Center for Advanced Intelligence Project", "public-ai-research-institute", "https://aip.riken.jp/news-list/?lang=en"),
    ("turing-institute", "Alan Turing Institute", "national-ai-institute", "https://www.turing.ac.uk/news"),
    ("ai2-incubator", "AI2 Incubator", "ai-startup-incubator", "https://www.ai2incubator.com/news"),
    ("schmidt-sciences", "Schmidt Sciences", "science-ai-philanthropy", "https://www.schmidtsciences.org/news/"),
    ("arc-institute", "Arc Institute", "ai-for-science-institute", "https://arcinstitute.org/news"),
    ("isomorphic-labs", "Isomorphic Labs", "ai-for-science-company", "https://www.isomorphiclabs.com/articles"),
    ("insitro", "insitro", "ai-biotechnology-company", "https://www.insitro.com/news"),
    ("recursion", "Recursion", "ai-biotechnology-company", "https://www.recursion.com/news"),
]

PEOPLE = [
    ("sam-altman", "Sam Altman", "ai-lab-executive", "https://blog.samaltman.com/"),
    ("greg-brockman", "Greg Brockman", "ai-lab-founder", "https://gregbrockman.com/"),
    ("ilya-sutskever", "Ilya Sutskever", "ai-researcher-founder", "https://www.cs.toronto.edu/~ilya/"),
    ("wojciech-zaremba", "Wojciech Zaremba", "ai-researcher-founder", "https://openai.com/index/wojciech-zaremba/"),
    ("john-schulman", "John Schulman", "ai-researcher", "https://joschu.net/"),
    ("andrej-karpathy", "Andrej Karpathy", "ai-researcher-educator", "https://karpathy.ai/"),
    ("dario-amodei", "Dario Amodei", "ai-lab-executive", "https://www.anthropic.com/people/dario-amodei"),
    ("daniela-amodei", "Daniela Amodei", "ai-lab-executive", "https://www.anthropic.com/people/daniela-amodei"),
    ("chris-olah", "Chris Olah", "interpretability-researcher", "https://colah.github.io/"),
    ("jan-leike", "Jan Leike", "ai-safety-researcher", "https://jan.leike.name/"),
    ("jared-kaplan", "Jared Kaplan", "ai-researcher", "https://krieger.jhu.edu/physics/directory/jared-kaplan/"),
    ("jack-clark", "Jack Clark", "ai-policy-executive", "https://jack-clark.net/"),
    ("demis-hassabis", "Demis Hassabis", "ai-lab-executive-researcher", "https://deepmind.google/about/leadership/demis-hassabis/"),
    ("shane-legg", "Shane Legg", "ai-researcher-founder", "https://deepmind.google/about/leadership/shane-legg/"),
    ("koray-kavukcuoglu", "Koray Kavukcuoglu", "ai-research-leader", "https://deepmind.google/about/leadership/koray-kavukcuoglu/"),
    ("david-silver", "David Silver", "reinforcement-learning-researcher", "https://www.davidsilver.uk/"),
    ("oriol-vinyals", "Oriol Vinyals", "ai-researcher", "https://vinyals.github.io/"),
    ("raia-hadsell", "Raia Hadsell", "robotics-ai-researcher", "https://deepmind.google/about/leadership/raia-hadsell/"),
    ("nando-de-freitas", "Nando de Freitas", "ai-researcher", "https://www.cs.ox.ac.uk/people/nando.defreitas/"),
    ("jeff-dean", "Jeff Dean", "ai-research-executive", "https://research.google/people/jeff/"),
    ("quoc-le", "Quoc V. Le", "ai-researcher", "https://research.google/people/quocvl/"),
    ("blaise-aguera-y-arcas", "Blaise Agüera y Arcas", "ai-researcher-executive", "https://research.google/people/blaisea/"),
    ("noam-shazeer", "Noam Shazeer", "ai-researcher-founder", "https://research.google/people/noamshazeer/"),
    ("yann-lecun", "Yann LeCun", "ai-scientist-executive", "https://yann.lecun.com/"),
    ("joelle-pineau", "Joelle Pineau", "ai-researcher-executive", "https://www.cs.mcgill.ca/~jpineau/"),
    ("rob-fergus", "Rob Fergus", "computer-vision-researcher", "https://cs.nyu.edu/~fergus/pmwiki/pmwiki.php"),
    ("mark-zuckerberg", "Mark Zuckerberg", "technology-executive", "https://about.meta.com/media-gallery/executives/mark-zuckerberg/"),
    ("satya-nadella", "Satya Nadella", "technology-executive", "https://news.microsoft.com/exec/satya-nadella/"),
    ("mustafa-suleyman", "Mustafa Suleyman", "ai-lab-executive-founder", "https://mustafa-suleyman.ai/"),
    ("kevin-scott", "Kevin Scott", "ai-technology-executive", "https://news.microsoft.com/exec/kevin-scott/"),
    ("peter-lee", "Peter Lee", "ai-research-executive", "https://www.microsoft.com/en-us/research/people/peterlee/"),
    ("sebastien-bubeck", "Sébastien Bubeck", "ai-researcher", "https://www.microsoft.com/en-us/research/people/sebubeck/"),
    ("elon-musk", "Elon Musk", "ai-company-founder", "https://x.com/elonmusk"),
    ("igor-babuschkin", "Igor Babuschkin", "ai-researcher-founder", "https://www.linkedin.com/in/igor-babuschkin-9bb5bab6/"),
    ("arthur-mensch", "Arthur Mensch", "ai-lab-executive-founder", "https://www.linkedin.com/in/arthur-mensch/"),
    ("guillaume-lample", "Guillaume Lample", "ai-researcher-founder", "https://fr.linkedin.com/in/guillaume-lample-7821095b"),
    ("timothee-lacroix", "Timothée Lacroix", "ai-researcher-founder", "https://fr.linkedin.com/in/timothee-lacroix-59517977"),
    ("aidan-gomez", "Aidan Gomez", "ai-lab-executive-researcher", "https://aidangomez.ca/"),
    ("nick-frosst", "Nick Frosst", "ai-researcher-founder", "https://nickfrosst.com/"),
    ("ivan-zhang", "Ivan Zhang", "ai-founder", "https://www.linkedin.com/in/1vnzh/"),
    ("yoav-shoham", "Yoav Shoham", "ai-researcher-founder", "https://ai.stanford.edu/~shoham/"),
    ("amnon-shashua", "Amnon Shashua", "ai-researcher-executive", "https://www.cs.huji.ac.il/~shashua/"),
    ("emad-mostaque", "Emad Mostaque", "generative-ai-founder", "https://emad.blog/"),
    ("david-holz", "David Holz", "generative-ai-founder", "https://www.midjourney.com/home"),
    ("cristobal-valenzuela", "Cristóbal Valenzuela", "generative-ai-founder", "https://runwayml.com/about"),
    ("alexandr-wang", "Alexandr Wang", "ai-infrastructure-executive", "https://scale.com/leadership"),
    ("nat-friedman", "Nat Friedman", "ai-investor-technologist", "https://nat.org/"),
    ("daniel-gross", "Daniel Gross", "ai-investor-founder", "https://dcgross.com/"),
    ("feifei-li", "Fei-Fei Li", "ai-researcher-founder", "https://profiles.stanford.edu/fei-fei-li"),
    ("justin-johnson", "Justin Johnson", "computer-vision-researcher", "https://web.eecs.umich.edu/~justincj/"),
    ("pieter-abbeel", "Pieter Abbeel", "robotics-ai-researcher-founder", "https://people.eecs.berkeley.edu/~pabbeel/"),
    ("sergey-levine", "Sergey Levine", "robotics-ai-researcher", "https://people.eecs.berkeley.edu/~svlevine/"),
    ("chelsea-finn", "Chelsea Finn", "robotics-ai-researcher", "https://ai.stanford.edu/~cbfinn/"),
    ("russell-tedrake", "Russ Tedrake", "robotics-ai-researcher", "https://groups.csail.mit.edu/robotics-center/people/tedrake.html"),
    ("rodney-brooks", "Rodney Brooks", "roboticist-founder", "https://rodneybrooks.com/"),
    ("raquel-urtasun", "Raquel Urtasun", "autonomous-systems-researcher-founder", "https://www.cs.toronto.edu/~urtasun/"),
    ("alex-kendall", "Alex Kendall", "autonomous-systems-founder", "https://wayve.ai/people/alex-kendall/"),
    ("daniela-rus", "Daniela Rus", "robotics-ai-researcher", "https://danielarus.csail.mit.edu/"),
    ("jim-fan", "Jim Fan", "embodied-ai-researcher", "https://www.jimfan.me/"),
    ("ashish-vaswani", "Ashish Vaswani", "ai-researcher-founder", "https://www.ashishvaswani.com/"),
    ("noam-brown", "Noam Brown", "ai-researcher", "https://noambrown.github.io/"),
    ("jakob-uszkoreit", "Jakob Uszkoreit", "ai-researcher-founder", "https://www.inceptive.life/team/jakob-uszkoreit"),
    ("lukasz-kaiser", "Lukasz Kaiser", "ai-researcher", "https://www.kasai.org/"),
    ("david-ha", "David Ha", "ai-researcher-founder", "https://otoro.net/"),
    ("shunyu-yao", "Shunyu Yao", "agentic-ai-researcher", "https://ysymyth.github.io/"),
    ("harrison-chase", "Harrison Chase", "agent-platform-founder", "https://www.langchain.com/about"),
    ("jerry-liu", "Jerry Liu", "agent-platform-founder", "https://www.llamaindex.ai/about"),
    ("clem-delangue", "Clément Delangue", "open-ai-platform-executive", "https://huggingface.co/clem"),
    ("thomas-wolf", "Thomas Wolf", "open-source-ai-researcher", "https://huggingface.co/ThomasWolf"),
    ("margaret-mitchell", "Margaret Mitchell", "responsible-ai-researcher", "https://huggingface.co/mmitchell"),
    ("stella-biderman", "Stella Biderman", "open-ai-researcher", "https://www.stellabiderman.com/"),
    ("lucile-saulnier", "Lucile Saulnier", "open-source-ai-researcher", "https://huggingface.co/lucile"),
    ("jeremy-howard", "Jeremy Howard", "ai-educator-researcher", "https://www.fast.ai/about/"),
    ("sebastian-raschka", "Sebastian Raschka", "ai-researcher-educator", "https://sebastianraschka.com/"),
    ("chip-huyen", "Chip Huyen", "ai-systems-author", "https://huyenchip.com/"),
    ("lilian-weng", "Lilian Weng", "ai-researcher-writer", "https://lilianweng.github.io/"),
    ("eugene-yan", "Eugene Yan", "machine-learning-engineer-writer", "https://eugeneyan.com/"),
    ("simon-willison", "Simon Willison", "ai-developer-writer", "https://simonwillison.net/"),
    ("swyx", "Shawn Wang", "ai-engineer-writer", "https://www.swyx.io/"),
    ("ethan-mollick", "Ethan Mollick", "ai-and-work-researcher", "https://www.oneusefulthing.org/"),
    ("gary-marcus", "Gary Marcus", "cognitive-scientist-ai-critic", "https://garymarcus.substack.com/"),
    ("melanie-mitchell", "Melanie Mitchell", "complexity-ai-researcher", "https://melaniemitchell.me/"),
    ("geoffrey-hinton", "Geoffrey Hinton", "deep-learning-researcher", "https://www.cs.toronto.edu/~hinton/"),
    ("yoshua-bengio", "Yoshua Bengio", "deep-learning-researcher", "https://yoshuabengio.org/"),
    ("richard-sutton", "Richard Sutton", "reinforcement-learning-researcher", "http://incompleteideas.net/"),
    ("jurgen-schmidhuber", "Jürgen Schmidhuber", "deep-learning-researcher", "https://people.idsia.ch/~juergen/"),
    ("judea-pearl", "Judea Pearl", "causal-ai-researcher", "https://bayes.cs.ucla.edu/jp_home.html"),
    ("michael-jordan", "Michael I. Jordan", "machine-learning-researcher", "https://people.eecs.berkeley.edu/~jordan/"),
    ("leslie-valiant", "Leslie Valiant", "theoretical-ai-researcher", "https://people.seas.harvard.edu/~valiant/"),
    ("daphne-koller", "Daphne Koller", "ai-researcher-founder", "https://ai.stanford.edu/~koller/"),
    ("andrew-ng", "Andrew Ng", "ai-educator-founder", "https://www.andrewng.org/"),
    ("ian-goodfellow", "Ian Goodfellow", "deep-learning-researcher", "https://www.iangoodfellow.com/"),
    ("alex-graves", "Alex Graves", "deep-learning-researcher", "https://www.cs.toronto.edu/~graves/"),
    ("chris-bishop", "Christopher Bishop", "machine-learning-researcher", "https://www.microsoft.com/en-us/research/people/cmbishop/"),
    ("david-mackay", "David MacKay", "machine-learning-scientist", "https://www.inference.org.uk/mackay/"),
    ("max-tegmark", "Max Tegmark", "ai-safety-researcher-founder", "https://space.mit.edu/home/tegmark/"),
    ("stuart-russell", "Stuart Russell", "ai-safety-researcher", "https://people.eecs.berkeley.edu/~russell/"),
    ("roman-yampolskiy", "Roman Yampolskiy", "ai-safety-researcher", "https://cecs.louisville.edu/ry/"),
    ("eliezar-yudkowsky", "Eliezer Yudkowsky", "ai-safety-writer-researcher", "https://www.yudkowsky.net/"),
    ("paul-christiano", "Paul Christiano", "ai-alignment-researcher", "https://paulfchristiano.com/"),
    ("holden-karnofsky", "Holden Karnofsky", "ai-governance-philanthropy", "https://www.cold-takes.com/"),
    ("ajeya-cotra", "Ajeya Cotra", "ai-scenarios-researcher", "https://www.planned-obsolescence.org/"),
    ("rohin-shah", "Rohin Shah", "ai-safety-researcher", "https://rohinshah.com/"),
    ("dylan-hadfield-menell", "Dylan Hadfield-Menell", "ai-safety-researcher", "https://people.csail.mit.edu/dhm/"),
    ("david-krueger", "David Krueger", "ai-safety-researcher", "https://www.davidscottkrueger.com/"),
    ("dan-hendrycks", "Dan Hendrycks", "ai-safety-researcher-founder", "https://danhendrycks.com/"),
    ("beth-barnes", "Beth Barnes", "ai-evaluation-researcher", "https://metr.org/about"),
    ("ben-garfinkel", "Ben Garfinkel", "ai-governance-researcher", "https://www.governance.ai/about/ben-garfinkel"),
    ("allan-dafoe", "Allan Dafoe", "ai-governance-researcher", "https://www.governance.ai/about/allan-dafoe"),
    ("helen-toner", "Helen Toner", "ai-policy-researcher", "https://cset.georgetown.edu/staff/helen-toner/"),
    ("timnit-gebru", "Timnit Gebru", "responsible-ai-researcher-founder", "https://www.dair-institute.org/team/"),
    ("joy-buolamwini", "Joy Buolamwini", "algorithmic-accountability-researcher", "https://www.poetofcode.com/"),
    ("meredith-whittaker", "Meredith Whittaker", "ai-policy-researcher", "https://ainowinstitute.org/author/meredith-whittaker"),
    ("kate-crawford", "Kate Crawford", "ai-society-researcher", "https://katecrawford.net/"),
    ("emily-bender", "Emily M. Bender", "computational-linguist-ai-critic", "https://faculty.washington.edu/ebender/"),
    ("arvind-narayanan", "Arvind Narayanan", "ai-policy-researcher", "https://www.cs.princeton.edu/~arvindn/"),
    ("sayash-kapoor", "Sayash Kapoor", "ai-policy-researcher", "https://www.sayashkapoor.com/"),
    ("percy-liang", "Percy Liang", "foundation-model-researcher", "https://cs.stanford.edu/~pliang/"),
    ("chris-manning", "Christopher Manning", "nlp-researcher", "https://nlp.stanford.edu/~manning/"),
    ("dan-jurafsky", "Dan Jurafsky", "nlp-researcher", "https://web.stanford.edu/~jurafsky/"),
    ("yoav-goldberg", "Yoav Goldberg", "nlp-researcher", "https://www.cs.biu.ac.il/~yogo/"),
    ("graham-neubig", "Graham Neubig", "nlp-researcher", "https://www.phontron.com/"),
    ("sasha-rush", "Sasha Rush", "nlp-researcher", "https://rush-nlp.com/"),
    ("dawn-song", "Dawn Song", "ai-security-researcher-founder", "https://people.eecs.berkeley.edu/~dawnsong/"),
    ("boaz-barak", "Boaz Barak", "theoretical-ai-researcher", "https://www.boazbarak.org/"),
    ("sanmi-koyejo", "Sanmi Koyejo", "responsible-ai-researcher", "https://sanmikoyejo.com/"),
    ("been-kim", "Been Kim", "interpretability-researcher", "https://beenkim.github.io/"),
    ("finale-doshi-velez", "Finale Doshi-Velez", "interpretable-ai-researcher", "https://finale.seas.harvard.edu/"),
]


def records(rows):
    return [
        {"slug": slug, "name": name, "category" if rows is ORGANIZATIONS else "role": kind, "url": url}
        for slug, name, kind, url in rows
    ]


def main() -> None:
    out = {
        "organizations": records(ORGANIZATIONS),
        "people": records(PEOPLE),
    }
    path = Path(__file__).resolve().parents[1] / "data" / "registry-candidates.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(out, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
    print(f"wrote {len(out['organizations'])} organizations and {len(out['people'])} people to {path}")


if __name__ == "__main__":
    main()
